trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
    - script: echo "Building the project"
      displayName: 'Build'

- job: Test
  displayName: 'Test Job'
  dependsOn: Build
  strategy:
    maxParallel: 1  # Set maxParallel to 1 to run jobs sequentially
  steps:
    - script: echo "Running tests"
      displayName: 'Run Tests'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Test
  steps:
    - script: echo "Deploying the project"
      displayName: 'Deploy'